#!/bin/bash
#
# Build CoreConfig & Associated Cert Generation
#

set -x
set -euo pipefail

. $NVM_DIR/nvm.sh

certbot certonly -v --standalone -d ${HostedDomain} --email ${HostedEmail} --non-interactive --agree-tos

/opt/tak/configureInDocker.sh init

