#!/bin/bash
#
# Upload a TAKServer Docker image to the correct ECR
#

# Drop preceding folders & remove extension
folder=$(basename -- "$1")
folder=${folder%.*}

if [[ ! "${folder:0:17}" == "takserver-docker-" ]]; then
  echo "Error: takserver-docker must start with takserver-docker-" >&2
  exit 1
fi

set -euo pipefail

unzip -o $1 -d /tmp/

echo "Extracted /tmp/${folder}"

VERSION=$(echo $folder | sed 's/takserver-docker-//' | tr '[:upper:]' '[:lower:]')

docker build -t takserver:${VERSION} -f /tmp/${folder}/docker/Dockerfile.takserver .

AWS_ACCOUNT=$(aws sts get-caller-identity --query Account --output text)

aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com

docker tag takserver:${VERSION} ${AWS_ACCOUNT}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/coe-ecr-tak:${VERSION}

docker push ${AWS_ACCOUNT}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/coe-ecr-tak:${VERSION}
